### ISSUE TITLE
Write developer's guide for user-defined categories

### ISSUE THREAD

**Issue by Tyler-Clemens** [tapis-project/tapisv3-cli#6]
- [ ] Mission (open-source, user-friendly, modularity, extensibility)
- [ ] Architectural overview
- [ ] Installing custom categories
- [ ] Writing custom categories
- [ ] Writing options
- [ ] Writing custom handlers
- [ ] Publishing packages

**Comment by nathandf** [comment]
Will write a Confluence doc for whole CLI
